#!/usr/bin/env bash

if [ -z "${GIT_HOOK_TOOLS_PATH+x}" ]; then
  declare -gr GIT_HOOK_TOOLS_PATH="."
fi
if [ -z "${GIT_HOOK_CONFIG_PATH+x}" ]; then
  declare -gr GIT_HOOK_CONFIG_PATH="setup/config"
fi

. "./setup/scripts/pre-commit.sh"