#!/usr/bin/env bash

# shell_pre_commit_check_git_compliance — Evaluates working tree stability via Git
# index checking to isolate and block execution streams if files are modified.
# 
# Description:
# - Refreshes the Git index to force a content-based evaluation, preventing false-positive
#   triggers caused by mere file timestamp (mtime) mutations from external automation.
# - Compares disk content against the index within a targeted dynamic scope of paths.
# - Intercepts the pre-commit gatekeeper by rendering a formatted blocking diagnostic
#   report if unstaged modifications are found, forcing the developer to explicitly
#   stage changes.
# 
# Arguments:
# - project_root_path:  The absolute path reference tracking the system workspace
#   root.
# - context_activity_message: A descriptive label injected dynamically into the stdout
#   report explaining the nature or driver of the automated workspace updates.
# - Array of paths:           Remaining dynamic positional arguments ($@) defining
#   specific files or directory contexts scoped for compliance evaluation.
# 
# Returns:
# - Renders an actionable blocking diagnostics console layout to stdout if the index
#   is unstable.
# 
# Return Codes:
# - 0: Index is stable; no unstaged content modifications detected within the targeted
#   paths.
# - 1: Unstaged modifications found; commit execution is explicitly blocked for review.
shell_pre_commit_check_git_compliance() {
  local project_root_path="${1}"
  local context_activity_message="${2}"
  shift
  shift
  local check_paths=("$@")
  local -a git_diff_paths=()


  local path=""
  for path in "${check_paths[@]}"; do
    if [ "${path}" != "" ]; then
      git_diff_paths+=("${project_root_path}/${path}")
    fi
  done

  # Pathspec Sanitization Gate If no paths are provided, or if the array contains
  # a single empty string artifact, fallback to the repository default root dot "."
  # pathspec to prevent Git fatal crashes.
  if [ "${#git_diff_paths[@]}" -eq 0 ] || { [ "${#git_diff_paths[@]}" -eq 1 ] && [ "${git_diff_paths[0]}" = "" ]; }; then
    git_diff_paths=(".")
  fi

  # 1. Forces Git to re-evaluate files on disk based on content, ignoring timestamp
  #    (mtime) changes generated by external automated updates.
  git update-index --refresh > /dev/null 2>&1


  # 2. Captures only the files that have pending actual text modifications
  local unstaged_files=$(git diff-files --name-only -- "${git_diff_paths[@]}" 2>/dev/null)
  local git_status=$?


  # 3. Operational Safe Guard Intercept If the git binary exits with an error status
  #    (e.g., repository locked, bad config), halt pipeline execution immediately
  #    to prevent silent failures.
  if [ ${git_status} -ne 0 ]; then
    echo "[FATAL_ERR] Git diff operation encountered an internal binary error."
    echo ""
    return 1
  fi


  if [ -n "${unstaged_files}" ]; then
    echo ""
    echo "================================================================================"
    echo "[ x ] :: COMMIT BLOCKED FOR REVIEW"
    echo "         Automated repository actions triggered the following modification:"
    echo ""
    echo "  >> ${context_activity_message} <<"
    echo "  The following files were modified and must be staged before committing:"
    echo ""

    # Renders the target file list using a precise process substitution pipeline
    # to guarantee clean line-by-line parsing without trailing whitespace artifacts.
    local unstable_file=""
    while IFS= read -r unstable_file; do
      if [ -n "${unstable_file}" ]; then
        echo "[ ! ] - ${unstable_file}"
      fi
    done < <(echo "${unstaged_files}")

    echo ""
    echo "[ERR] :: Commit interrupted!"
    echo "       > Please review 'git diff', stage the fixes (git add), and commit again."
    echo ""
    return 1
  fi

  return 0
}
